---
####################################################################
# Example :  Journal Volume Playbook
####################################################################
- name: Journal Volume Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ####################################################################
    # Task 1 : Create a Journal Volume using required details
    ####################################################################
    - name: Create a Journal Volume using required details
      hitachivantara.vspone_block.vsp.hv_journal_volume:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          journal_id: 37
          ldev_ids: [1993, 1994]
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
