---
####################################################################
# Ansible Playbook to create on-premises HUR pair on Hitachi VSP storage
####################################################################
- name: HUR
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars_files:
    - ansible_vault_storage_var.yml
  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"
      
  tasks:
  - name: Create a HUR pair in new copy group
    hitachivantara.vspone_block.vsp.hv_hur:
      state: "present"
      connection_info: "{{ connection_info }}"
      secondary_connection_info: "{{ secondary_connection_info }}"
      spec:
        copy_group_name: "{{ copy_group_name }}"
        copy_pair_name: "{{ copy_pair_name }}"
        primary_volume_id: "{{ pvol_id }}"
        primary_volume_journal_id: "{{ pvol_jnl_id }}"
        secondary_volume_journal_id: "{{ svol_jnl_id }}"
        secondary_pool_id: "{{ secondary_pool_id }}"
        local_device_group_name: "{{ local_device_group_name }}"
        remote_device_group_name: "{{ remote_device_group_name }}"
        allocate_new_consistency_group: true
        secondary_storage_serial_number: "{{ secondary_storage_serial }}"
        secondary_iscsi_targets:
          - name: "{{ target_name }}"
            port: "{{ port1_name }}"
            lun_id: "{{ lun_id }}"
        mirror_unit_id: "{{ mirror_unit_id }}"
        is_data_reduction_force_copy: false
        path_group_id: "{{ path_group_id }}"
    register: result
  - name: Debug the result variable
    ansible.builtin.debug:
        var: result